Canvas.MAX_ANIMATE_SPEED = 5;  //最大动画速度
Canvas.ANIMATE_SPEED = 1; 
Canvas.WIDTH = 1000;  //默认画板宽度
Canvas.HEIGHT = 550;  //默认画板高度
Canvas.DELAY_TIME = 600; //默认延迟时间
Canvas.REFRESH_TIME = 24; //默认画面刷新时间
Canvas.BORDER = "2px solid #0AF";

Shape.BACKCOLOR = "ABC";  //默认图形填充背景色
Shape.EDGECOLOR = "000";  //默认图形边框颜色
Shape.TEXTCOLOR = "F00";  //默认图形填充文本颜色
Shape.TEXT = "shape";    //默认图新填充的文本内容
Shape.WIDTH = 50;       //默认图形宽度
Shape.HEIGHT = 50;      //默认图形高度
Shape.START_X = 0;           //默认图新位置
Shape.START_Y = 0;
Shape.AIM_X = 500;      //默认图新移动目标位置
Shape.AIM_Y = 500;
Shape.MOVE_SPEED = 5;  //默认图新移动速度
Shape.MOVE_PATH = "LINE"; //默认图新移动方式(直线)
Shape.FONT = '10px sans-serif';
Shape.TEXTALIGN = "center";
Shape.TEXTBASELINE = 'middle';
Shape.LINECOLOR = "000";   //默认线条颜色
Shape.END_X = 100;  //图形末尾位置
Shape.END_Y = 100;
Shape.LINEWIDTH = 2;  //线条宽度
Shape.RADIUS = 50;
Shape.X = 100;
Shape.Y = 100;
Shape.EDGEWIDTH = 3;
var Positive_Integer = /^[0-9]*[1-9][0-9]*$/;
